version: "2"

networks:
  lsstar:
    driver: bridge

services:
  php_apache:
    image: webdevops/php-apache:7.4
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../:/var/www/html/lsstarsite"

  # php_lsstar:
  #   build: .
  #   container_name: php_lsstar
  #   working_dir: /usr/share/nginx/html
  #   volumes:
  #     - ../:/usr/share/nginx/html
  #   #command: "php artisan serve --host=0.0.0.0 --port=2030"
  #   ports:
  #     - "2030:2030"
  #   networks:
  #     - lsstar
