version: "2"

networks:
  internal:
    driver: bridge

services:
  sitelsstar:
    container_name: "sitelsstar"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "${PATHPESSOAL}/lsstar-site/vue:/app"
    command: "npm run serve"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.sitelsstar.rule=Host(`sitelsstar.localhost`)
      - traefik.http.services.sitelsstar.loadbalancer.server.port=8080
